# Generated by Django 3.2.5 on 2021-08-11 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commentsapp', '0002_doctoremails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctoremails',
            options={'verbose_name_plural': 'DoctorEmails'},
        ),
    ]
